### ISSUE TITLE
Issues with install of RSAP

### ISSUE THREAD

**Issue by surya731** [piersharding/RSAP#1]
Piers:
I am trying to install RSAP on WIN7 64bit machine and having a really hard time. I am trying to follow the steps but it is having some issues. I installed devtools package and other dependencies like reshape and yaml. I also installed rtools.

I am pasting below some of output of the install. I tried from Rstudio as will as the R interface that came with the 3.2.4 install.

Can you help? Much appreciated in advance. 

Satish Vadlamani

> > install_github('RSAP', username='piersharding', args=c("--configure-args='--with-nwrfcsdk-include=/home/piers/code/sap/nwrfcsdk/include --with-nwrfcsdk-lib=/home/piers/code/sap/nwrfcsdk/lib' --no-clean-on-error"))
> > Downloading GitHub repo piersharding/RSAP@master
> > from URL https://api.github.com/repos/piersharding/RSAP/zipball/master
> > Installing RSAP
> > Installing 1 package: Rcpp
> > package ‘Rcpp’ successfully unpacked and MD5 sums checked
> > Warning: cannot remove prior installation of package ‘Rcpp’
> > "C:/PROGRA~1/R/R-32~1.4/bin/i386/R" --no-site-file --no-environ --no-save --no-restore  \
> >   CMD INSTALL  \
> >   "C:/Users/Satish/AppData/Local/Temp/RtmpaQ9Oa0/devtools172034a22ec3/piersharding-RSAP-0a06486"  \
> >   --library="C:/Users/Satish/Documents/R/win-library/3.2" --install-tests  \
> >   --configure-args='--with-nwrfcsdk-include=/home/piers/code/sap/nwrfcsdk/include  \
> >   --with-nwrfcsdk-lib=/home/piers/code/sap/nwrfcsdk/lib' --no-clean-on-error

Warning: unknown option '--with-nwrfcsdk-lib=/home/piers/code/sap/nwrfcsdk/lib''
- installing _source_ package 'RSAP' ...
  *\* libs
  Warning: this package has a non-empty 'configure.win' file,
  so building only the main architecture

gcc -m32 -I"C:/PROGRA~1/R/R-32~1.4/include" -DNDEBUG -I. -I"C:/nwrfcsdk/include" -DSAPwithUNICODE -DUNICODE -D_UNICODE -D_AFXDLL -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -DSAPonNT -DSAP_PLATFORM_MAKENAME=ntintel     -I"d:/RCompile/r-compiling/local/local323/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c RSAP.c -o RSAP.o
In file included from RSAP.c:41:0:
C:/nwrfcsdk/include/sapnwrfc.h:28:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
RSAP.c: In function 'u8to16c':
RSAP.c:133:12: warning: variable 'rc' set but not used [-Wunused-but-set-variable]
RSAP.c: In function 'u8to16':
RSAP.c:150:12: warning: variable 'rc' set but not used [-Wunused-but-set-variable]
RSAP.c: In function 'u8to16r':
RSAP.c:167:12: warning: variable 'rc' set but not used [-Wunused-but-set-variable]
RSAP.c: In function 'u16to8c':
RSAP.c:184:12: warning: variable 'rc' set but not used [-Wunused-but-set-variable]
RSAP.c: In function 'u16to8':
RSAP.c:208:12: warning: variable 'rc' set but not used [-Wunused-but-set-variable]
RSAP.c: At top level:
C:/nwrfcsdk/include/sapuc.h:853:24: warning: 'sccsidU16' defined but not used [-Wunused-variable]
gcc -m32 -shared -s -static-libgcc -o RSAP.dll tmp.def RSAP.o -L. -LC:/nwrfcsdk/lib -lsapnwrfc -llibsapucum -Ld:/RCompile/r-compiling/local/local323/lib/i386 -Ld:/RCompile/r-compiling/local/local323/lib -LC:/PROGRA~1/R/R-32~1.4/bin/i386 -lR
installing to C:/Users/Satish/Documents/R/win-library/3.2/RSAP/libs/i386
*\* R
*\* tests
*\* preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  there is no package called 'Rcpp'
Error : package 'reshape' could not be loaded
ERROR: lazy loading failed for package 'RSAP'
Error: Command failed (1)
In addition: Warning message:
Username parameter is deprecated. Please use piersharding/RSAP

> require("RSAP")
> Loading required package: RSAP
> Error in inDL(x, as.logical(local), as.logical(now), ...) :
>   unable to load shared object 'C:/Users/Satish/Documents/R/win-library/3.2/RSAP/libs/i386/RSAP.dll':
>   LoadLibrary failure:  The specified module could not be found.

**Comment by piersharding** [comment]
By the look of it it hasn't linked to the sapnwrfcsdk - you need to make sure that it is inC:/nwrfcsdk.  You may also need to copy the C:/nwrfcsdk/lib DLLs into the system32 directory.

I don't use windows so I can't really give you much advice.

Cheers,
Piers Harding.

**Comment by surya731** [comment]
Piers:
Thank you for taking the time to answer this question. I tried all of that. I will keep trying and let you know.  I will contact Basis friends who may be able to help with this.

I added to the PATH variable the directory where the dlls are. That did not help either.
Thanks,
Satish

**Comment by surya731** [comment]
Piers:
I would imagine that windows users are using this package? Do you have information on this?
Thanks,
Satish

**Comment by piersharding** [comment]
You may get some leads on the SDN forums if you look at how people are compiling other extensions like for sapnwrfc for Perl, Python and Ruby.  You should also find the RSAP.dll that is compiled and use a dependency walker to determine whether or not all the necessary libraries are found on your windows system.

Cheers,
Piers Harding.

**Comment by surya731** [comment]
Piers:
Yes. I am doing all of these. I have not yet taken RSAP.dll through
dependency walker but I will.
Thank you.
Satish

On Fri, Mar 25, 2016 at 9:41 AM, Piers Harding <notifications@github.com>
wrote:

> You may get some leads on the SDN forums if you look at how people are
> compiling other extensions like for sapnwrfc for Perl, Python and Ruby. You
> should also find the RSAP.dll that is compiled and use a dependency walker
> to determine whether or not all the necessary libraries are found on your
> windows system.
>
> Cheers,
> Piers Harding.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/piersharding/RSAP/issues/1#issuecomment-201357891>
>



-- 

Satish Vadlamani

**Comment by rpremraj** [comment]
@surya731 This comment does not solve your problem, but FYI, some of us tried compiling RSAP on 64bit R and failed as well. On 32bit, it works charmingly.
