### ISSUE TITLE
bytes and xstrings handled incorrectly

### ISSUE THREAD

**Issue by morganw3** [piersharding/RSAP#10]
There is an issue in get_byte_value and (I believe) get_xstring_value. The buffer is treated as a SAP_UC when it should be as a vector of raw bytes or a raw string. The attached patch allows invoking a method that returns a table with a byte value succeed where it previously failed with "embedded nul". I haven't run across an xstring but I believe it could fail in a similar manner. Sorry I'm not familiar enough with git to do this as a pull request!

[patch.txt](https://github.com/piersharding/RSAP/files/2363809/patch.txt)

**Comment by piersharding** [comment]
Hi @morganw3 - thanks for this, I have applied the patch and pushed version 0.11.  Could you please test, and let me know.

Thanks,
Piers.

**Comment by morganw3** [comment]
Looks great, thanks!
