### ISSUE TITLE
nwrfcsdk needs an include folder, what should be in there?

### ISSUE THREAD

**Issue by martinhyy** [piersharding/RSAP#2]
Hi  @Piers,

I'm trying to install RSAP in R. As constructed I put a bunch of files in C:/nwrfcsdk/lib folder, however when I use `install.packages("RSAP")`, I still got an ERROR message says 

> C:/nwrfcsdk/include  include directory does not exist.

May I ask what files are needed in include folder?

I'm using windows 10, R version 3.4.2 64 bit

Thanks

**Comment by piersharding** [comment]
Hi -

You need to obtain the NW RFC SDK from SAP.  This usually comes from SAP installation media or OSS in a compressed archive file format (.CAR/.SAR file).

Cheers,
Piers Harding.

**Comment by martinhyy** [comment]
Hi @piersharding ,

My colleague gave me the lib files and I put them all in the lib folder like the screenshot below:

![image](https://user-images.githubusercontent.com/6981963/33247347-402064d8-d382-11e7-8205-a3cacd2e322d.png)

Due to the current access limitation, I can't really obtain NW RFC SDK from SAP and my colleague told me the files that were given to me is NW RFC SDK from SAP. So wondering in the **include** folder, do I need something else? 

Thanks

**Comment by piersharding** [comment]
Yes -you need the header files from the NW RFC SDK that go with the lib files.  Your technical representative for SAP should have access to get the SDK for you.

Cheers,
Piers.
