### ISSUE TITLE
Use different delimiter than semicolon in RSAPReadTable

### ISSUE THREAD

**Issue by gllrt** [piersharding/RSAP#4]
In a table I whose data I need to access semicolons are contained in string fields and the current version of RSAPReadTable yields a wrong output.

Having looked into the code of RSAPReadTable the problem seems to be the choice of semicolon as the delimiter. If I understand the RFC_READ_TABLE correctly, there is no option to have the field content enquoted.
 
As a workaround one could use a more obscure character such as "‡" as the delimiter.

**Comment by piersharding** [comment]
Hi -please see the latest commit, I have added the optional 'delimiter' parameter which defaults to ';'.  Let me know if it works for you.

**Comment by gllrt** [comment]
Hi, indeed your latest commit solves the issue nicely.
