### ISSUE TITLE
No floats returned by function

### ISSUE THREAD

**Issue by morganw3** [piersharding/RSAP#8]
Trying to execute the function "BAPI_COSTESTIMATE_ITEMIZATION", does not return any floating-point numbers for the RESULT dataframe. Calling the exact same method and parameters with PyRFC returns Decimal objects with the correct values as returned by a CK13 itemization with equivalent parameters.

**Comment by piersharding** [comment]
Hi -
I do not have any access to SAP systems anymore, but am willing to help anyone else create patches for this.

**Comment by morganw3** [comment]
Found the problem - in get_bcd_value and get_num_value, the call to atof needs to be converted to - atof(CHAR(u16to8((SAP_UC *)buffer)))))

**Comment by piersharding** [comment]
hi @morganw3  - thanks for this, I have pushed up the fix.  Please check it and let me know.

**Comment by morganw3** [comment]
@piersharding this fix works (for me).
